### ISSUE TITLE
How to extract the five features?

### ISSUE THREAD

**Issue by ChShenLi** [ashafaei/ubc3v#3]
In the paper IV.B,you said “collect five different features for each class and then generate a vector f∈R1032,the concatenation of all 24 features per class”.What the consist of vector f?How to extracted the features?The paper not given more details...and I can not find enough number of them.Could you give more details?

**Comment by ashafaei** [comment]
Hello @ChShenLi,
Quoting the paper:

> (i) the median of each dimension, 
> (ii) the covariance matrix, 
> (iii) the eigenvalues of the covariance matrix, 
> (iv) the standard deviation of each dimension, and 
> (v) the minimum and the maximum of each dimension for each class.

The median for each feature is R^3 (X, Y, Z) = 3
The covariance matrix is R^3x3 = 9
The eigenvalues are 3 x R^1 = 3
The STD of each dimension is 3 x R^1 = 3
The min and max of each dim is 2 x 3 x R^1 = 6

That is 24 features per class. We also have 43 classes -> 24x43 = 1032

- I first classify the depth image into 43 classes.
- I then project the depth images into the reference point-cloud so that I can merge all the depth images into a single universal representation.
- Then for each class, I calculate the above features.
- Then I do a regression to predict the actual joint location (for each joint).

**Comment by ChShenLi** [comment]
Wow! So it means just input a vector of 24 dimention to do a regression for each class.
I find the depth-image in the dataset have the alpha channel.
Is it has been processed before the experience?What the pre-process is?
I'm trying to rebuild this system recently,but it always have to much noice in the input depth-image.

**Comment by ChShenLi** [comment]
Hello,@ashafaei.
Why we should calculate features for each class(43),but just do regeression for each joint(18)? The dataset just have the groundtruth for 18 joints,but the data for other classes is [1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1],and the joint_location for them is (0 0 0),is that have another means?  
Or we just need to do regression for the 18 joints only using the above feature(18*24)?
