### ISSUE TITLE
1.03 scale factor in "covert_to_zdepth.m"

### ISSUE THREAD

**Issue by jiangwei221** [ashafaei/ubc3v#4]
Hi,
Thanks for the great work!
I found there is a scale factor in covert_to_zdepth.m.
`output_args = (double(input_args(:, :, 1))./255 .* (800-50) + 50)*1.03;`
Could you give a hint what the 1.03 is?

Thanks!

**Comment by jiangwei221** [comment]
I think it's for visualization

**Comment by ashafaei** [comment]
Hello @jiangwei221 
The images are generated using Maya, but they are being reconstructed using Kinect camera parameters. Furthermore, each Kinect camera has different intrinsic camera parameters due to the manufacturing process, but an average over all the Kinect cameras will give the same camera parameters as the Maya renders. The `1.03` is to account for the discrepancy between the two configurations -- the specific reconstruction parameters that I took from my Kinect and the one that I used to generate the images. It only becomes relevant when you are reconstructing the point-cloud.
