### ISSUE TITLE
How to open one example locally

### ISSUE THREAD

**Issue by GonzaloMoreno** [ashafaei/ubc3v#7]
Hi: First at all, I would like to thank you for the effort that you have made to put this dataset available for everyone. I would like to play with one example because in my laptop I do not have resources enough to work with all the example and I don´t need all the dataset. I am trying to open the demo file with Octave in windows 10

However, I am having problems to open that example. I have changed the path in the config.m path of this way:
easy_pose_path = 'C:\Users\gonzalo.moreno\Documents\Novartis\easy-pose\train\1\'

Why am I failing in working with the demo file?

Regards,

Gonzalo

**Comment by ashafaei** [comment]
Hello Gonzalo,
It's been a while since I looked at the folder hierarchy of this project. But if I remember correctly, it doesn't matter if you have all the files or only a subset. If you look at the demo code, there's a part where I say:

```matlab
instances = load_multicam('easy-pose', 'train', 150, 1:10);
```

If you only have the folder '1' from the 'easy-pose' 'train', subset, you could just say:

```matlab
instances = load_multicam('easy-pose', 'train', 1, 1:10);
```
This example will load 10 images from the folder 1.
Furthermore, if you only have the first frame of the first folder, you might as well say:
```matlab
instances = load_multicam('easy-pose', 'train', 1, [1]);
```
So you'd be loading only the first file from the first folder of the train subset of the easy-pose.

The path in config should point to the root of the directory, not individual sub-directories.

Let me know if I can provide more help.

Cheers,
Alireza

**Comment by GonzaloMoreno** [comment]
Thanks. I could open it
